#!/usr/bin/env bash
# Generate a bpftrace script that classifies the game's I/O completion ports: which ones only
# ever see same-process PostQueuedCompletionStatus traffic ("pure", eligible for an in-process
# queue) and which get files/sockets bound, job objects associated, handles duplicated,
# alertable dequeues or direct waits.
#
#   C <ns> <tid> <port> <threads>          NtCreateIoCompletion (returned handle)
#   O <ns> <tid> <port>                    NtOpenIoCompletion (named port)
#   B <ns> <tid> <file> <port> <key>       NtSetInformationFile(FileCompletionInformation)
#   R <ns> <tid> <file> <port>             NtSetInformationFile(FileReplaceCompletionInformation)
#   J <ns> <tid> <job> <port>              NtSetInformationJobObject(AssociateCompletionPort)
#   D <ns> <tid> <src> <srcproc> <dstproc> <options>   NtDuplicateObject of a known port
#   X <ns> <tid> <port>                    NtClose of a known port
#   every 5 s: @set/@setx[port] posts, @rm[port] NtRemoveIoCompletion,
#              @ex[port, alertable] NtRemoveIoCompletionEx, @q[port] NtQueryIoCompletion,
#              @wso[port] / @wmo[port] direct waits on a known port
#
# Usage: tools/wwm/gen_iocp_purity.sh <runner-dir> [out.bt]; report: tools/wwm/iocp_purity_report.py
set -euo pipefail

runner="${1:?usage: gen_iocp_purity.sh <runner-dir> [out.bt]}"
ntdll="${runner%/}/files/lib/wine/x86_64-unix/ntdll.so"
[ -f "$ntdll" ] || { echo "error: no unix ntdll.so at $ntdll" >&2; exit 1; }
out="${2:-$(dirname "$0")/iocp_purity_$(basename "${runner%/}").bt}"

cat > "$out" <<EOF
// Generated by tools/wwm/gen_iocp_purity.sh for: $runner
BEGIN { printf("#profiler-bpftrace pid={pid} begin_ns=%llu\\n", nsecs); }
tracepoint:sched:sched_process_exit /pid == {pid} && tid == {pid}/ { exit(); }

uprobe:$ntdll:NtCreateIoCompletion /pid == {pid}/ { @cp[tid] = arg0; @ct[tid] = arg3; }
uretprobe:$ntdll:NtCreateIoCompletion /pid == {pid} && @cp[tid]/
{
    if (retval == 0) {
        \$h = *uptr((uint64 *)@cp[tid]);
        @isport[\$h] = 1;
        printf("C %llu %d %lx %d\\n", nsecs, tid, \$h, (uint32)@ct[tid]);
    }
    delete(@cp[tid]); delete(@ct[tid]);
}
uprobe:$ntdll:NtOpenIoCompletion /pid == {pid}/ { @op[tid] = arg0; }
uretprobe:$ntdll:NtOpenIoCompletion /pid == {pid} && @op[tid]/
{
    if (retval == 0) {
        \$h = *uptr((uint64 *)@op[tid]);
        @isport[\$h] = 1;
        printf("O %llu %d %lx\\n", nsecs, tid, \$h);
    }
    delete(@op[tid]);
}
// FILE_COMPLETION_INFORMATION { HANDLE CompletionPort; ULONG_PTR CompletionKey; }
uprobe:$ntdll:NtSetInformationFile /pid == {pid} && (arg4 == 30 || arg4 == 61)/
{
    if (arg4 == 30) {
        printf("B %llu %d %lx %lx %lx\\n", nsecs, tid, arg0, *uptr((uint64 *)arg2), *uptr((uint64 *)(arg2 + 8)));
    } else {
        printf("R %llu %d %lx %lx\\n", nsecs, tid, arg0, arg2 ? *uptr((uint64 *)arg2) : (uint64)0);
    }
}
// JOBOBJECT_ASSOCIATE_COMPLETION_PORT { PVOID CompletionKey; HANDLE CompletionPort; }
uprobe:$ntdll:NtSetInformationJobObject /pid == {pid} && arg1 == 7/
{
    printf("J %llu %d %lx %lx\\n", nsecs, tid, arg0, *uptr((uint64 *)(arg2 + 8)));
}
// NtDuplicateObject( src_process, src, dst_process, dst*, access, attributes, options ): options is the 7th argument
uprobe:$ntdll:NtDuplicateObject /pid == {pid} && @isport[arg1]/
{
    printf("D %llu %d %lx %lx %lx %x\\n", nsecs, tid, arg1, arg0, arg2, (uint32)*uptr((uint64 *)(reg("sp") + 8)));
}
uprobe:$ntdll:NtClose /pid == {pid} && @isport[arg0]/
{
    printf("X %llu %d %lx\\n", nsecs, tid, arg0);
    delete(@isport[arg0]);
}

uprobe:$ntdll:NtSetIoCompletion /pid == {pid}/ { @set[arg0] = count(); }
uprobe:$ntdll:NtSetIoCompletionEx /pid == {pid}/ { @setx[arg0] = count(); }
uprobe:$ntdll:NtRemoveIoCompletion /pid == {pid}/ { @rm[arg0] = count(); }
uprobe:$ntdll:NtRemoveIoCompletionEx /pid == {pid}/ { @ex[arg0, (uint8)arg5] = count(); }
uprobe:$ntdll:NtQueryIoCompletion /pid == {pid}/ { @q[arg0] = count(); }
uprobe:$ntdll:NtWaitForSingleObject /pid == {pid} && @isport[arg0]/ { @wso[arg0] = count(); }
uprobe:$ntdll:NtWaitForMultipleObjects /pid == {pid}/
{
    \$n = arg0 < 4 ? arg0 : 4;
    if (\$n > 0 && @isport[*uptr((uint64 *)arg1)]) { @wmo[*uptr((uint64 *)arg1)] = count(); }
    if (\$n > 1 && @isport[*uptr((uint64 *)(arg1 + 8))]) { @wmo[*uptr((uint64 *)(arg1 + 8))] = count(); }
    if (\$n > 2 && @isport[*uptr((uint64 *)(arg1 + 16))]) { @wmo[*uptr((uint64 *)(arg1 + 16))] = count(); }
    if (\$n > 3 && @isport[*uptr((uint64 *)(arg1 + 24))]) { @wmo[*uptr((uint64 *)(arg1 + 24))] = count(); }
}

interval:s:5
{
    printf("#flush %llu\\n", nsecs);
    print(@set); clear(@set);
    print(@setx); clear(@setx);
    print(@rm); clear(@rm);
    print(@ex); clear(@ex);
    print(@q); clear(@q);
    print(@wso); clear(@wso);
    print(@wmo); clear(@wmo);
}

END { clear(@cp); clear(@ct); clear(@op); clear(@isport); }
EOF
echo "wrote $out"
