#!/usr/bin/env bash
# Generate a runner-specific bpftrace script that takes a per-thread census of every
# unix-side Nt* entry point the game reaches, plus requested-vs-actual Sleep()
# durations and wall time spent inside the main wait calls.
#
# The point is an A/B of *what the game asks Wine to do* during the loading window,
# GE-Proton10-34 vs. GE-Proton11, instead of tuning one primitive at a time.
#
# Usage:
#   tools/wwm/gen_nt_census.sh ~/.local/share/lutris/runners/wine/GE-Proton10-34
#   sudo python3 proton_profiler.py record --name wwm.exe --wait \
#        --bpftrace-script tools/wwm/nt_census_GE-Proton10-34.bt
#
# Every probe is emitted explicitly with its function name as a string literal.
# A wildcard probe keyed on the `func` builtin makes bpftrace symbolize each
# instruction pointer in userspace at print time; against a Wine process that
# grew bpftrace to tens of GB and it never exited.
#
# Overhead: one uprobe hit per Nt* call (~1-2 us each). It is the same on both
# runners, so relative comparisons hold, but do not read absolute load times off
# an instrumented run.
set -euo pipefail

runner="${1:?usage: gen_nt_census.sh <runner-dir> [out.bt]}"
ntdll="${runner%/}/files/lib/wine/x86_64-unix/ntdll.so"
if [ ! -f "$ntdll" ]; then
    echo "error: no unix ntdll.so at $ntdll" >&2
    exit 1
fi
out="${2:-$(dirname "$0")/nt_census_$(basename "${runner%/}").bt}"

# NtCurrentTeb is a TEB accessor, not a syscall: hundreds of thousands of calls
# per second with no diagnostic value.
mapfile -t funcs < <(nm -D --defined-only "$ntdll" | awk '$2 == "T" && $3 ~ /^Nt/ && $3 != "NtCurrentTeb" { print $3 }' | sort -u)
if [ "${#funcs[@]}" -eq 0 ]; then
    echo "error: no exported Nt* functions found in $ntdll" >&2
    exit 1
fi

waits=(NtWaitForSingleObject NtWaitForMultipleObjects NtRemoveIoCompletion
       NtRemoveIoCompletionEx NtWaitForAlertByThreadId NtDelayExecution)

{
    echo "// Generated by tools/wwm/gen_nt_census.sh for: $runner"
    echo 'BEGIN { printf("#profiler-bpftrace pid={pid} begin_ns=%llu\n", nsecs); }'
    echo
    echo "// Stop by ourselves when the game's main thread exits, so a missed stop"
    echo "// signal can never leave this tracer running."
    echo 'tracepoint:sched:sched_process_exit /pid == {pid} && tid == {pid}/ { exit(); }'
    echo
    echo "// Every Nt* call, per thread."
    for f in "${funcs[@]}"; do
        echo "uprobe:$ntdll:$f /pid == {pid}/ { @nt[tid, \"$f\"] = count(); }"
    done
    echo
    echo "// IOCP posts by completion key and, for Boost.Asio operations, by handler type:"
    echo "// the posted value is a win_iocp_operation (OVERLAPPED at +0, next_ at +32,"
    echo "// func_ at +40), so func_ is the address of that handler's completion routine."
    echo "uprobe:$ntdll:NtSetIoCompletion /pid == {pid}/"
    echo "{"
    echo '    @post_key[arg1] = count();'
    echo '    if (arg2 != 0) { @post_fn[arg1, *uptr((uint64 *)(arg2 + 40))] = count(); }'
    echo "}"
    echo
    echo "// Due time of every waitable-timer arm: relative due times as a histogram (us),"
    echo "// absolute ones counted separately."
    echo "uprobe:$ntdll:NtSetTimer /pid == {pid}/"
    echo "{"
    echo '    $due = *uptr((int64 *)arg1);'
    echo '    if ($due < 0) { @timer_due_us[tid] = hist((uint64)(-$due) / 10); }'
    echo '    else { @timer_due_abs[tid] = count(); }'
    echo "}"
    echo
    echo "// Sleep()/SleepEx(): requested duration (us; -2 = absolute timeout, -1 = infinite)."
    echo "uprobe:$ntdll:NtDelayExecution /pid == {pid}/"
    echo "{"
    echo '    $t = arg1 ? *uptr((int64 *)arg1) : 0;'
    echo '    @dly_req[tid] = arg1 ? ($t <= 0 ? (int64)((uint64)(-$t) / 10) : -2) : -1;'
    echo "}"
    echo
    echo "// Wall time inside the blocking entry points (and Sleep), per thread and per call."
    for f in "${waits[@]}"; do
        echo "uprobe:$ntdll:$f /pid == {pid}/ { @w_start[tid, \"$f\"] = nsecs; }"
        echo "uretprobe:$ntdll:$f /pid == {pid} && @w_start[tid, \"$f\"]/"
        echo "{"
        echo "    \$us = (uint64)(nsecs - @w_start[tid, \"$f\"]) / 1000;"
        echo "    @wait_us[\"$f\"] = hist(\$us);"
        echo "    @wait_total_us[tid, \"$f\"] = sum(\$us);"
        if [ "$f" = "NtDelayExecution" ]; then
            echo "    @sleep_req_us[tid, @dly_req[tid]] = count();"
            echo "    @sleep_actual_us[tid] = hist(\$us);"
            echo "    delete(@dly_req[tid]);"
        fi
        echo "    delete(@w_start[tid, \"$f\"]);"
        echo "}"
    done
    cat <<'EOF'

interval:s:2
{
    printf("#flush %llu\n", nsecs);
    print(@nt);              clear(@nt);
    print(@sleep_req_us);    clear(@sleep_req_us);
    print(@sleep_actual_us); clear(@sleep_actual_us);
    print(@wait_us);         clear(@wait_us);
    print(@wait_total_us);   clear(@wait_total_us);
    print(@post_key);        clear(@post_key);
    print(@post_fn);         clear(@post_fn);
    print(@timer_due_us);    clear(@timer_due_us);
    print(@timer_due_abs);   clear(@timer_due_abs);
}

END
{
    clear(@dly_req);
    clear(@w_start);
}
EOF
} > "$out"

echo "wrote $out (${#funcs[@]} Nt* probes)"
